### ISSUE TITLE
Compatibility issues with numPy

### ISSUE THREAD

**Issue by vsht** [gudrunhe/secdec#30]
Hi,

I have pySecDec installed using the official way
```
python3 -m pip install --user 'pip>=20.1'
python3 -m pip install --user --upgrade pySecDec
```
but it seems like due to some compatibility issues with the recent versions of numPy,
asymptotic expansion doesn't work anymore. Trying to run the `make_regions_ebr`  example I get

```
#python generate_make_regions_ebr.py

Total number of regions: 2
/home/vs/.local/lib/python3.11/site-packages/pySecDec/misc.py:439: SymPyDeprecationWarning: 

The string fallback in sympify() is deprecated.

To explicitly convert the string form of an object, use
sympify(str(obj)). To add define sympify behavior on custom
objects, use sympy.core.sympify.converter or define obj._sympy_
(see the sympify() docstring).

sympify() performed the string fallback resulting in the following string:

' + (0)'

See https://docs.sympy.org/latest/explanation/active-deprecations.html#deprecated-sympify-string-fallback
for details.

This has been deprecated since SymPy version 1.6. It
will be removed in a future version of SymPy.

  return sp.sympify(a)
Region (0,1), smallness parameter lowest order is 0
Traceback (most recent call last):
  File "/media/Data/Projects/Other/pySecDec/secdec/examples/make_regions_ebr/generate_make_regions_ebr.py", line 10, in <module>
    regions_generators = make_regions(
                         ^^^^^^^^^^^^^
  File "/home/vs/.local/lib/python3.11/site-packages/pySecDec/make_regions.py", line 495, in make_regions
    for i,term in enumerate(series):
  File "/home/vs/.local/lib/python3.11/site-packages/pySecDec/make_regions.py", line 323, in expand_region
    derivative = derive_prod(poly_list,numerator,index,polynomial_name_indices)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vs/.local/lib/python3.11/site-packages/pySecDec/make_regions.py", line 248, in derive_prod
    expolist = np.zeros(number_of_symbols,dtype=np.int)
                                                ^^^^^^
  File "/usr/lib64/python3.11/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'?
```

I'm running Fedora 37 with numpy 1.24.3.

**Comment by magv** [comment]
This should be solved in pySecDec 1.6. Vlad, could you please re-check?

(Note that Python 3.8+ is now needed for pySecDec).

**Comment by vsht** [comment]
Now everything works as expected :)

**Comment by magv** [comment]
Thanks for checking.
