### ISSUE TITLE
Error while running "sum_package"

### ISSUE THREAD

**Issue by dehorstmann** [gudrunhe/secdec#33]
Hi,

I try to run the following code:

```
#!/usr/bin/env python3
import pySecDec as psd
loopint = psd.LoopIntegralFromPropagators(
  loop_momenta = ['l1','l2'],
  external_momenta = ['q'],
  propagators = ['(l2)**2','(l1 + l2)**2','(l1 - q)**2'],
  powerlist = [1,1,1],
  replacement_rules = [('q*q', 'sqrq')]
)
psd.loop_package(
    name = 'B101110',
    loop_integral = loopint,
    real_parameters = ['sqrq'],
    requested_orders = [0],
)
```

which generates the error

```
running "sum_package" for B101110
running "make_package" for "B101110_integral"
number of primary sectors before symmetry finding: 3
number of primary sectors after symmetry finding (iterative): 1
number of primary sectors after symmetry finding (light Pak): 1
number of primary sectors after symmetry finding (full Pak): 1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/dhorstmann/sciebo/Doktor/Projekte/BtoEtaC/magerya-capp2021Org/code/secdec-files/B101110.generate.py", line 10, in <module>
    psd.loop_package(
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/loop_integral/loop_package.py", line 358, in loop_package
    make_package_return_value = package_generator(**LoopPackage(
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/make_package.py", line 374, in make_package
    sum_package(
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/code_writer/sum_package.py", line 444, in sum_package
    parse_template_tree(template_sources, name, replacements_in_files, filesystem_replacements)
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/code_writer/template_parser.py", line 209, in parse_template_tree
    os.mkdir(this_target_directory)
FileExistsError: [Errno 17] File exists: 'B101110'
running "sum_package" for B101110
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/dhorstmann/sciebo/Doktor/Projekte/BtoEtaC/magerya-capp2021Org/code/secdec-files/B101110.generate.py", line 10, in <module>
    psd.loop_package(
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/loop_integral/loop_package.py", line 358, in loop_package
    make_package_return_value = package_generator(**LoopPackage(
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/make_package.py", line 374, in make_package
    sum_package(
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/code_writer/sum_package.py", line 444, in sum_package
    parse_template_tree(template_sources, name, replacements_in_files, filesystem_replacements)
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/code_writer/template_parser.py", line 209, in parse_template_tree
    os.mkdir(this_target_directory)
FileExistsError: [Errno 17] File exists: 'B101110'
running "sum_package" for B101110
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/dhorstmann/sciebo/Doktor/Projekte/BtoEtaC/magerya-capp2021Org/code/secdec-files/B101110.generate.py", line 10, in <module>
    psd.loop_package(
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/loop_integral/loop_package.py", line 358, in loop_package
    make_package_return_value = package_generator(**LoopPackage(
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/make_package.py", line 374, in make_package
    sum_package(
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/code_writer/sum_package.py", line 444, in sum_package
    parse_template_tree(template_sources, name, replacements_in_files, filesystem_replacements)
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/code_writer/template_parser.py", line 209, in parse_template_tree
    os.mkdir(this_target_directory)
FileExistsError: [Errno 17] File exists: 'B101110'
running "sum_package" for B101110
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/dhorstmann/sciebo/Doktor/Projekte/BtoEtaC/magerya-capp2021Org/code/secdec-files/B101110.generate.py", line 10, in <module>
    psd.loop_package(
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/loop_integral/loop_package.py", line 358, in loop_package
    make_package_return_value = package_generator(**LoopPackage(
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/make_package.py", line 374, in make_package
    sum_package(
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/code_writer/sum_package.py", line 444, in sum_package
    parse_template_tree(template_sources, name, replacements_in_files, filesystem_replacements)
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/code_writer/template_parser.py", line 209, in parse_template_tree
    os.mkdir(this_target_directory)
FileExistsError: [Errno 17] File exists: 'B101110'
running "sum_package" for B101110
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/dhorstmann/sciebo/Doktor/Projekte/BtoEtaC/magerya-capp2021Org/code/secdec-files/B101110.generate.py", line 10, in <module>
    psd.loop_package(
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/loop_integral/loop_package.py", line 358, in loop_package
    make_package_return_value = package_generator(**LoopPackage(
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/make_package.py", line 374, in make_package
    sum_package(
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/code_writer/sum_package.py", line 444, in sum_package
    parse_template_tree(template_sources, name, replacements_in_files, filesystem_replacements)
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/code_writer/template_parser.py", line 209, in parse_template_tree
    os.mkdir(this_target_directory)
FileExistsError: [Errno 17] File exists: 'B101110'
running "sum_package" for B101110
computing Jacobian determinant for primary sector 0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/dhorstmann/sciebo/Doktor/Projekte/BtoEtaC/magerya-capp2021Org/code/secdec-files/B101110.generate.py", line 10, in <module>
    psd.loop_package(
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/loop_integral/loop_package.py", line 358, in loop_package
    make_package_return_value = package_generator(**LoopPackage(
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/make_package.py", line 374, in make_package
    sum_package(
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/code_writer/sum_package.py", line 444, in sum_package
    parse_template_tree(template_sources, name, replacements_in_files, filesystem_replacements)
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/code_writer/template_parser.py", line 209, in parse_template_tree
    os.mkdir(this_target_directory)
FileExistsError: [Errno 17] File exists: 'B101110'
running "sum_package" for B101110
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/dhorstmann/sciebo/Doktor/Projekte/BtoEtaC/magerya-capp2021Org/code/secdec-files/B101110.generate.py", line 10, in <module>
    psd.loop_package(
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/loop_integral/loop_package.py", line 358, in loop_package
    make_package_return_value = package_generator(**LoopPackage(
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/make_package.py", line 374, in make_package
    sum_package(
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/code_writer/sum_package.py", line 444, in sum_package
    parse_template_tree(template_sources, name, replacements_in_files, filesystem_replacements)
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/code_writer/template_parser.py", line 209, in parse_template_tree
    os.mkdir(this_target_directory)
FileExistsError: [Errno 17] File exists: 'B101110'
running "sum_package" for B101110
running "sum_package" for B101110
running "make_package" for "B101110_integral"
number of primary sectors before symmetry finding: 3
number of primary sectors after symmetry finding (iterative): 1
number of primary sectors after symmetry finding (light Pak): 1
number of primary sectors after symmetry finding (full Pak): 1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/dhorstmann/sciebo/Doktor/Projekte/BtoEtaC/magerya-capp2021Org/code/secdec-files/B101110.generate.py", line 10, in <module>
    psd.loop_package(
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/loop_integral/loop_package.py", line 358, in loop_package
    make_package_return_value = package_generator(**LoopPackage(
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/make_package.py", line 374, in make_package
    sum_package(
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/code_writer/sum_package.py", line 476, in sum_package
    template_replacements = [_generate_one_term(
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/code_writer/sum_package.py", line 476, in <listcomp>
    template_replacements = [_generate_one_term(
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/code_writer/sum_package.py", line 167, in _generate_one_term
    mp = make_package(**package_generator._asdict())
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/code_writer/make_package.py", line 1970, in make_package
    pool = Pool(processes)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

This is only part of the message, though. It doesn't stop generating similar messages, even if I let it run for days. 

And, yes, I did delete the directory `B101110` that was generated by previous runs. If I don't delete it, I get the following error:

```
running "sum_package" for B101110
Traceback (most recent call last):
  File "/Users/dhorstmann/sciebo/Doktor/Projekte/BtoEtaC/magerya-capp2021Org/code/secdec-files/./B101110.generate.py", line 10, in <module>
    psd.loop_package(
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/loop_integral/loop_package.py", line 358, in loop_package
    make_package_return_value = package_generator(**LoopPackage(
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/make_package.py", line 374, in make_package
    sum_package(
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/code_writer/sum_package.py", line 444, in sum_package
    parse_template_tree(template_sources, name, replacements_in_files, filesystem_replacements)
  File "/Users/dhorstmann/Library/Python/3.9/lib/python/site-packages/pySecDec/code_writer/template_parser.py", line 209, in parse_template_tree
    os.mkdir(this_target_directory)
FileExistsError: [Errno 17] File exists: 'B101110'
```

I am running this on a MacBook Pro 2021 M1, but I have no issues during installation or while running `./generate_easy.py`, `./generate_box1L.py`, and `./generate_banana_3mass.py`, that are provided in your examples.

My pySecDec version is `1.6.post1`.

The above code is a minimal version of an example provided by @magv ([see here](https://indico.desy.de/event/26814/timetable/#20210410.detailed)).

Cheers,
Dennis

**Comment by magv** [comment]
You just need to wrap the main part of the script into a `if __name__ == "__main__"` like this:
```python
#!/usr/bin/env python3
import pySecDec as psd
if __name__ == "__main__":
    loopint = psd.LoopIntegralFromPropagators(
      loop_momenta = ['l1','l2'],
      external_momenta = ['q'],
      propagators = ['(l2)**2','(l1 + l2)**2','(l1 - q)**2'],
      powerlist = [1,1,1],
      replacement_rules = [('q*q', 'sqrq')]
    )
    psd.loop_package(
        name = 'B101110',
        loop_integral = loopint,
        real_parameters = ['sqrq'],
        requested_orders = [0],
    )
```
... without this Python's [multiprocessing module](https://docs.python.org/3/library/multiprocessing.html) doesn't work.

Sorry that I didn't include this that back then.

Please check if this works for you.

**Comment by dehorstmann** [comment]
Yes, it works. Thanks a lot!

**Comment by vsht** [comment]
> You just need to wrap the main part of the script into a `if __name__ == "__main__"` like this:

Hi Vitaly,

is this something universal or more like a Mac thing? On different Linux machines I never needed this line and had pySecDec
working without any issues. It was Dennis' M1 Macbook where we first encountered this issue. And even then his original script
flawlessly worked on my Fedora with the latest pySecDec release. So I'm now a bit confused.

Cheers,
Vlad

**Comment by magv** [comment]
It is needed whenever multiprocessing is used, i.e. when `processes` is set to more than 1, or if `processes` is unset, in which case the default is to use the number of CPUs allocated to the process or the number of CPUs the machine has. So, in theory, the same fix should be needed on Linux too -- if it's not, that's more of a bonus than a feature :)

**Comment by vsht** [comment]
Thanks a lot for the detailed explanation! In that case I definitely need to update the generating scripts for pySecDec in FeynHelpers.
